INPUT_TIMESTEPS = 2
TIMESTEP_PLANES = 9
PLANE_WIDTH = 7
PLANE_HEIGHT = 7
USED_LAYOUT="smallGrid.lay"
SMART_GHOST=True
BASTARD=FALSE

REPLAY_MEMORY_SIZE=20000
MIN_REPLAY_MEMORY_SIZE=512
MINIBATCH_SIZE=128
DISCOUNT = 0.999
UPDATE_TARGET_EVERY=1

LEARNING_RATE=1e-5
DECAY=0
MOMENTUM=0.9

GAME_MOVE_LIMIT=float("inf")
FOOD_REWARD=10
CAPSULE_REWARD=0
WIN_REWARD=500
KILL_REWARD=50

DIE_PENALTY=-200
TIME_PENALTY =-1
RUN_GRAPHICS=True#True
EPSILON=0.2
EPSILON_TIMES=0.9999
EPSILON_FLOOR=0.05
NUM_RANDOM_GAMES=0
